# Spring Boot 应用配置
spring:
  # 应用基本信息
  application:
    name: student-management-system
  
  # 数据源配置（使用H2内存数据库）
  datasource:
    url: jdbc:h2:mem:studentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
  
  # H2 数据库控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
  
  # SQL 初始化配置
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  # Jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  
  # 国际化配置
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 日志配置
logging:
  level:
    com.example.studentmanagement: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/student-management.log
    max-size: 10MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 应用信息
info:
  app:
    name: 学生管理系统
    description: 基于Spring Boot的学生信息管理系统
    version: 1.0.0
    author: System
  java:
    version: ${java.version}
  spring:
    version: ${spring-boot.version}